package com.example.ui.localization

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf
import com.example.data.settings.AppLanguage

/**
 * Small, dependency-free localization layer for the product UI. API prompts and
 * user-created content are intentionally not translated.
 */
data class AppStrings(
    val language: AppLanguage,
    val appName: String,
    val brandByline: String,
    val secureAgent: String,
    val connectToHcnsec: String,
    val enterApiKey: String,
    val apiKeyHint: String,
    val oneTimeSetup: String,
    val validating: String,
    val connectedModels: (Int) -> String,
    val unlockedSuite: String,
    val reasoningCoding: String,
    val artifactsAgents: String,
    val visionRealtime: String,
    val keystoreSecurity: String,
    val settings: String,
    val languageLabel: String,
    val english: String,
    val persian: String,
    val newChat: String,
    val searchConversations: String,
    val workspaces: String,
    val pinned: String,
    val recentConversations: String,
    val matchingConversations: String,
    val settingsApiKeys: String,
    val aiWorkspace: String,
    val uploadZip: String,
    val exportMarkdown: String,
    val regenerate: String,
    val emptyTitle: String,
    val emptySubtitle: String,
    val analyzeZipTitle: String,
    val analyzeZipSubtitle: String,
    val compareVersionsTitle: String,
    val compareVersionsSubtitle: String,
    val refactorTitle: String,
    val refactorSubtitle: String,
    val reasoningTitle: String,
    val reasoningSubtitle: String,
    val messagePlaceholder: String,
    val thoughtProcess: String,
    val copyThoughtProcess: String,
    val copied: String,
    val liveExecution: String,
    val executionReport: String,
    val steps: (Int, Int) -> String,
    val workspace: String,
    val filesTree: String,
    val projectAnalysis: String,
    val searchFiles: String,
    val chatWithWorkspace: String,
    val askAboutFile: String,
    val projectArchitecture: String,
    val structureOverview: String
)

private val englishStrings = AppStrings(
    language = AppLanguage.ENGLISH,
    appName = "Salvia-H.Ai",
    brandByline = "SalarSalvia · private intelligence workspace",
    secureAgent = "Secure autonomous AI agent · powered by your HCNSEC account",
    connectToHcnsec = "Connect to HCNSEC",
    enterApiKey = "Enter your HCNSEC API key",
    apiKeyHint = "Stored encrypted on this device",
    oneTimeSetup = "One-time setup · hardware-backed Android Keystore",
    validating = "Validating with HCNSEC…",
    connectedModels = { count -> "Connected · $count models ready" },
    unlockedSuite = "HCNSEC intelligence suite",
    reasoningCoding = "Reasoning + coding",
    artifactsAgents = "Artifacts + agents",
    visionRealtime = "Vision + realtime",
    keystoreSecurity = "Encrypted at rest with Android Keystore. Your key is never logged.",
    settings = "Settings",
    languageLabel = "Language",
    english = "English",
    persian = "فارسی",
    newChat = "New chat",
    searchConversations = "Search conversations…",
    workspaces = "PROJECT WORKSPACES",
    pinned = "PINNED",
    recentConversations = "RECENT CONVERSATIONS",
    matchingConversations = "MATCHING CONVERSATIONS",
    settingsApiKeys = "Settings & API keys",
    aiWorkspace = "SalarSalvia · AI workspace",
    uploadZip = "Upload ZIP",
    exportMarkdown = "Export as Markdown",
    regenerate = "Regenerate response",
    emptyTitle = "What will we create today?",
    emptySubtitle = "Deep analysis, code, documents, and invention workflows — in one calm workspace.",
    analyzeZipTitle = "Analyze a project ZIP",
    analyzeZipSubtitle = "Map files, architecture, risks, and next steps",
    compareVersionsTitle = "Compare project versions",
    compareVersionsSubtitle = "Merge the strongest ideas into a golden build",
    refactorTitle = "Refactor code deeply",
    refactorSubtitle = "Improve architecture, performance, and reliability",
    reasoningTitle = "Solve a hard problem",
    reasoningSubtitle = "Follow a rigorous step-by-step reasoning path",
    messagePlaceholder = "Message Salvia-H.Ai…",
    thoughtProcess = "Thought process",
    copyThoughtProcess = "Copy thought process",
    copied = "Copied",
    liveExecution = "Agent live execution",
    executionReport = "Agent execution report",
    steps = { completed, total -> "$completed/$total steps" },
    workspace = "Workspace",
    filesTree = "Files & tree",
    projectAnalysis = "Project analysis",
    searchFiles = "Search files in project…",
    chatWithWorkspace = "Chat with this workspace agent",
    askAboutFile = "Ask Salvia about this file",
    projectArchitecture = "Project architecture",
    structureOverview = "Structure overview"
)

private val persianStrings = englishStrings.copy(
    language = AppLanguage.PERSIAN,
    brandByline = "SalarSalvia · فضای هوشمند خصوصی شما",
    secureAgent = "ایجنت هوشمند امن · متصل به حساب HCNSEC شما",
    connectToHcnsec = "اتصال به HCNSEC",
    enterApiKey = "کلید API سرویس HCNSEC را وارد کنید",
    apiKeyHint = "به‌صورت رمزنگاری‌شده روی همین دستگاه ذخیره می‌شود",
    oneTimeSetup = "راه‌اندازی یک‌باره · محافظت‌شده با Android Keystore",
    validating = "در حال اعتبارسنجی با HCNSEC…",
    connectedModels = { count -> "متصل شد · $count مدل آماده است" },
    unlockedSuite = "مجموعه هوش HCNSEC",
    reasoningCoding = "استدلال + کدنویسی",
    artifactsAgents = "آرتیفکت + ایجنت",
    visionRealtime = "بینایی + بلادرنگ",
    keystoreSecurity = "کلید با Android Keystore رمزنگاری می‌شود و هرگز لاگ نخواهد شد.",
    settings = "تنظیمات",
    languageLabel = "زبان",
    english = "English",
    persian = "فارسی",
    newChat = "گفت‌وگوی جدید",
    searchConversations = "جست‌وجوی گفتگوها…",
    workspaces = "فضاهای پروژه",
    pinned = "سنجاق‌شده",
    recentConversations = "گفتگوهای اخیر",
    matchingConversations = "گفتگوهای یافت‌شده",
    settingsApiKeys = "تنظیمات و کلیدهای API",
    aiWorkspace = "SalarSalvia · فضای کار هوشمند",
    uploadZip = "آپلود ZIP",
    exportMarkdown = "خروجی Markdown",
    regenerate = "تولید دوباره پاسخ",
    emptyTitle = "امروز چه چیزی می‌سازیم؟",
    emptySubtitle = "تحلیل عمیق، کد، سند و مسیرهای اختراع؛ در یک فضای آرام و حرفه‌ای.",
    analyzeZipTitle = "تحلیل فایل ZIP پروژه",
    analyzeZipSubtitle = "ساختار فایل‌ها، معماری، ریسک‌ها و قدم‌های بعدی",
    compareVersionsTitle = "مقایسه نسخه‌های پروژه",
    compareVersionsSubtitle = "ترکیب بهترین ایده‌ها در نسخه نهایی طلایی",
    refactorTitle = "بازآرایی عمیق کد",
    refactorSubtitle = "بهبود معماری، سرعت و قابلیت اطمینان",
    reasoningTitle = "حل یک مسئله دشوار",
    reasoningSubtitle = "مشاهده مسیر استدلال مرحله‌به‌مرحله",
    messagePlaceholder = "پیام برای Salvia-H.Ai…",
    thoughtProcess = "فرآیند فکر کردن",
    copyThoughtProcess = "کپی فرآیند فکر کردن",
    copied = "کپی شد",
    liveExecution = "اجرای زنده ایجنت",
    executionReport = "گزارش اجرای ایجنت",
    steps = { completed, total -> "$completed از $total مرحله" },
    workspace = "فضای پروژه",
    filesTree = "فایل‌ها و درخت پروژه",
    projectAnalysis = "تحلیل پروژه",
    searchFiles = "جست‌وجو در فایل‌های پروژه…",
    chatWithWorkspace = "گفتگو با ایجنت این پروژه",
    askAboutFile = "از Salvia درباره این فایل بپرس",
    projectArchitecture = "معماری پروژه",
    structureOverview = "نمای کلی ساختار"
)

val LocalAppStrings = compositionLocalOf { englishStrings }

@Composable
fun rememberAppStrings(language: AppLanguage): AppStrings =
    if (language == AppLanguage.PERSIAN) persianStrings else englishStrings
